# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'AnimalsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimalsApp
  pod 'Alamofire', '~> 5.0'
  pod 'SDWebImage', '~> 5.0'

  target 'AnimalsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimalsAppUITests' do
    # Pods for testing
  end

end
